//
// Generated file, do not edit! Created by nedtool 5.2 from common/addr.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __ADDR_M_H
#define __ADDR_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <cstdint>
// }}

/**
 * Class generated from <tt>common/addr.msg:6</tt> by nedtool.
 * <pre>
 * message Address
 * {
 *     uint8_t address;
 * }
 * </pre>
 */
class Address : public ::omnetpp::cMessage
{
  protected:
    uint8_t address;

  private:
    void copy(const Address& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Address&);

  public:
    Address(const char *name=nullptr, short kind=0);
    Address(const Address& other);
    virtual ~Address();
    Address& operator=(const Address& other);
    virtual Address *dup() const override {return new Address(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getAddress() const;
    virtual void setAddress(uint8_t address);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Address& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Address& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ADDR_M_H

