//
// Generated file, do not edit! Created by nedtool 5.2 from common/imm16.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __IMM16_M_H
#define __IMM16_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <cstdint>
// }}

/**
 * Class generated from <tt>common/imm16.msg:6</tt> by nedtool.
 * <pre>
 * message Imm16
 * {
 *     int16_t imm16;
 * }
 * </pre>
 */
class Imm16 : public ::omnetpp::cMessage
{
  protected:
    int16_t imm16;

  private:
    void copy(const Imm16& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Imm16&);

  public:
    Imm16(const char *name=nullptr, short kind=0);
    Imm16(const Imm16& other);
    virtual ~Imm16();
    Imm16& operator=(const Imm16& other);
    virtual Imm16 *dup() const override {return new Imm16(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int16_t getImm16() const;
    virtual void setImm16(int16_t imm16);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Imm16& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Imm16& obj) {obj.parsimUnpack(b);}


#endif // ifndef __IMM16_M_H

